# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mateng/third_party/test_rocksdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mateng/third_party/test_rocksdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateng/third_party/test_rocksdb/CMakeFiles /home/mateng/third_party/test_rocksdb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mateng/third_party/test_rocksdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_simple_example

# Build rule for target.
c_simple_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c_simple_example
.PHONY : c_simple_example

# fast build rule for target.
c_simple_example/fast:
	$(MAKE) -f CMakeFiles/c_simple_example.dir/build.make CMakeFiles/c_simple_example.dir/build
.PHONY : c_simple_example/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_multiget

# Build rule for target.
test_multiget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multiget
.PHONY : test_multiget

# fast build rule for target.
test_multiget/fast:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/build
.PHONY : test_multiget/fast

#=============================================================================
# Target rules for targets named test_tailing

# Build rule for target.
test_tailing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tailing
.PHONY : test_tailing

# fast build rule for target.
test_tailing/fast:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/build
.PHONY : test_tailing/fast

micro-test/test_multiget.o: micro-test/test_multiget.cpp.o
.PHONY : micro-test/test_multiget.o

# target to build an object file
micro-test/test_multiget.cpp.o:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.o
.PHONY : micro-test/test_multiget.cpp.o

micro-test/test_multiget.i: micro-test/test_multiget.cpp.i
.PHONY : micro-test/test_multiget.i

# target to preprocess a source file
micro-test/test_multiget.cpp.i:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.i
.PHONY : micro-test/test_multiget.cpp.i

micro-test/test_multiget.s: micro-test/test_multiget.cpp.s
.PHONY : micro-test/test_multiget.s

# target to generate assembly for a file
micro-test/test_multiget.cpp.s:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.s
.PHONY : micro-test/test_multiget.cpp.s

micro-test/test_tailing.o: micro-test/test_tailing.cpp.o
.PHONY : micro-test/test_tailing.o

# target to build an object file
micro-test/test_tailing.cpp.o:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.o
.PHONY : micro-test/test_tailing.cpp.o

micro-test/test_tailing.i: micro-test/test_tailing.cpp.i
.PHONY : micro-test/test_tailing.i

# target to preprocess a source file
micro-test/test_tailing.cpp.i:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.i
.PHONY : micro-test/test_tailing.cpp.i

micro-test/test_tailing.s: micro-test/test_tailing.cpp.s
.PHONY : micro-test/test_tailing.s

# target to generate assembly for a file
micro-test/test_tailing.cpp.s:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.s
.PHONY : micro-test/test_tailing.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_multiget"
	@echo "... c_simple_example"
	@echo "... test_tailing"
	@echo "... test"
	@echo "... micro-test/test_multiget.o"
	@echo "... micro-test/test_multiget.i"
	@echo "... micro-test/test_multiget.s"
	@echo "... micro-test/test_tailing.o"
	@echo "... micro-test/test_tailing.i"
	@echo "... micro-test/test_tailing.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

