# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lanvent/projects/GraphDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lanvent/projects/GraphDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lanvent/projects/GraphDB/CMakeFiles /home/lanvent/projects/GraphDB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lanvent/projects/GraphDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_tailing

# Build rule for target.
test_tailing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tailing
.PHONY : test_tailing

# fast build rule for target.
test_tailing/fast:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/build
.PHONY : test_tailing/fast

#=============================================================================
# Target rules for targets named test_multiget

# Build rule for target.
test_multiget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_multiget
.PHONY : test_multiget

# fast build rule for target.
test_multiget/fast:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/build
.PHONY : test_multiget/fast

#=============================================================================
# Target rules for targets named test_simple

# Build rule for target.
test_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_simple
.PHONY : test_simple

# fast build rule for target.
test_simple/fast:
	$(MAKE) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/build
.PHONY : test_simple/fast

#=============================================================================
# Target rules for targets named test_strawman_join

# Build rule for target.
test_strawman_join: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_strawman_join
.PHONY : test_strawman_join

# fast build rule for target.
test_strawman_join/fast:
	$(MAKE) -f CMakeFiles/test_strawman_join.dir/build.make CMakeFiles/test_strawman_join.dir/build
.PHONY : test_strawman_join/fast

#=============================================================================
# Target rules for targets named test_graphdb

# Build rule for target.
test_graphdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_graphdb
.PHONY : test_graphdb

# fast build rule for target.
test_graphdb/fast:
	$(MAKE) -f CMakeFiles/test_graphdb.dir/build.make CMakeFiles/test_graphdb.dir/build
.PHONY : test_graphdb/fast

#=============================================================================
# Target rules for targets named test_dbcache

# Build rule for target.
test_dbcache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dbcache
.PHONY : test_dbcache

# fast build rule for target.
test_dbcache/fast:
	$(MAKE) -f CMakeFiles/test_dbcache.dir/build.make CMakeFiles/test_dbcache.dir/build
.PHONY : test_dbcache/fast

micro-test/test_multiget.o: micro-test/test_multiget.cpp.o

.PHONY : micro-test/test_multiget.o

# target to build an object file
micro-test/test_multiget.cpp.o:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.o
.PHONY : micro-test/test_multiget.cpp.o

micro-test/test_multiget.i: micro-test/test_multiget.cpp.i

.PHONY : micro-test/test_multiget.i

# target to preprocess a source file
micro-test/test_multiget.cpp.i:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.i
.PHONY : micro-test/test_multiget.cpp.i

micro-test/test_multiget.s: micro-test/test_multiget.cpp.s

.PHONY : micro-test/test_multiget.s

# target to generate assembly for a file
micro-test/test_multiget.cpp.s:
	$(MAKE) -f CMakeFiles/test_multiget.dir/build.make CMakeFiles/test_multiget.dir/micro-test/test_multiget.cpp.s
.PHONY : micro-test/test_multiget.cpp.s

micro-test/test_tailing.o: micro-test/test_tailing.cpp.o

.PHONY : micro-test/test_tailing.o

# target to build an object file
micro-test/test_tailing.cpp.o:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.o
.PHONY : micro-test/test_tailing.cpp.o

micro-test/test_tailing.i: micro-test/test_tailing.cpp.i

.PHONY : micro-test/test_tailing.i

# target to preprocess a source file
micro-test/test_tailing.cpp.i:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.i
.PHONY : micro-test/test_tailing.cpp.i

micro-test/test_tailing.s: micro-test/test_tailing.cpp.s

.PHONY : micro-test/test_tailing.s

# target to generate assembly for a file
micro-test/test_tailing.cpp.s:
	$(MAKE) -f CMakeFiles/test_tailing.dir/build.make CMakeFiles/test_tailing.dir/micro-test/test_tailing.cpp.s
.PHONY : micro-test/test_tailing.cpp.s

test/test_dbcache.o: test/test_dbcache.cpp.o

.PHONY : test/test_dbcache.o

# target to build an object file
test/test_dbcache.cpp.o:
	$(MAKE) -f CMakeFiles/test_dbcache.dir/build.make CMakeFiles/test_dbcache.dir/test/test_dbcache.cpp.o
.PHONY : test/test_dbcache.cpp.o

test/test_dbcache.i: test/test_dbcache.cpp.i

.PHONY : test/test_dbcache.i

# target to preprocess a source file
test/test_dbcache.cpp.i:
	$(MAKE) -f CMakeFiles/test_dbcache.dir/build.make CMakeFiles/test_dbcache.dir/test/test_dbcache.cpp.i
.PHONY : test/test_dbcache.cpp.i

test/test_dbcache.s: test/test_dbcache.cpp.s

.PHONY : test/test_dbcache.s

# target to generate assembly for a file
test/test_dbcache.cpp.s:
	$(MAKE) -f CMakeFiles/test_dbcache.dir/build.make CMakeFiles/test_dbcache.dir/test/test_dbcache.cpp.s
.PHONY : test/test_dbcache.cpp.s

test/test_graphdb.o: test/test_graphdb.cpp.o

.PHONY : test/test_graphdb.o

# target to build an object file
test/test_graphdb.cpp.o:
	$(MAKE) -f CMakeFiles/test_graphdb.dir/build.make CMakeFiles/test_graphdb.dir/test/test_graphdb.cpp.o
.PHONY : test/test_graphdb.cpp.o

test/test_graphdb.i: test/test_graphdb.cpp.i

.PHONY : test/test_graphdb.i

# target to preprocess a source file
test/test_graphdb.cpp.i:
	$(MAKE) -f CMakeFiles/test_graphdb.dir/build.make CMakeFiles/test_graphdb.dir/test/test_graphdb.cpp.i
.PHONY : test/test_graphdb.cpp.i

test/test_graphdb.s: test/test_graphdb.cpp.s

.PHONY : test/test_graphdb.s

# target to generate assembly for a file
test/test_graphdb.cpp.s:
	$(MAKE) -f CMakeFiles/test_graphdb.dir/build.make CMakeFiles/test_graphdb.dir/test/test_graphdb.cpp.s
.PHONY : test/test_graphdb.cpp.s

test/test_simple.o: test/test_simple.cpp.o

.PHONY : test/test_simple.o

# target to build an object file
test/test_simple.cpp.o:
	$(MAKE) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/test/test_simple.cpp.o
.PHONY : test/test_simple.cpp.o

test/test_simple.i: test/test_simple.cpp.i

.PHONY : test/test_simple.i

# target to preprocess a source file
test/test_simple.cpp.i:
	$(MAKE) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/test/test_simple.cpp.i
.PHONY : test/test_simple.cpp.i

test/test_simple.s: test/test_simple.cpp.s

.PHONY : test/test_simple.s

# target to generate assembly for a file
test/test_simple.cpp.s:
	$(MAKE) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/test/test_simple.cpp.s
.PHONY : test/test_simple.cpp.s

test/test_strawman_join.o: test/test_strawman_join.cpp.o

.PHONY : test/test_strawman_join.o

# target to build an object file
test/test_strawman_join.cpp.o:
	$(MAKE) -f CMakeFiles/test_strawman_join.dir/build.make CMakeFiles/test_strawman_join.dir/test/test_strawman_join.cpp.o
.PHONY : test/test_strawman_join.cpp.o

test/test_strawman_join.i: test/test_strawman_join.cpp.i

.PHONY : test/test_strawman_join.i

# target to preprocess a source file
test/test_strawman_join.cpp.i:
	$(MAKE) -f CMakeFiles/test_strawman_join.dir/build.make CMakeFiles/test_strawman_join.dir/test/test_strawman_join.cpp.i
.PHONY : test/test_strawman_join.cpp.i

test/test_strawman_join.s: test/test_strawman_join.cpp.s

.PHONY : test/test_strawman_join.s

# target to generate assembly for a file
test/test_strawman_join.cpp.s:
	$(MAKE) -f CMakeFiles/test_strawman_join.dir/build.make CMakeFiles/test_strawman_join.dir/test/test_strawman_join.cpp.s
.PHONY : test/test_strawman_join.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test_tailing"
	@echo "... test_multiget"
	@echo "... rebuild_cache"
	@echo "... test_simple"
	@echo "... test_strawman_join"
	@echo "... test_graphdb"
	@echo "... test_dbcache"
	@echo "... micro-test/test_multiget.o"
	@echo "... micro-test/test_multiget.i"
	@echo "... micro-test/test_multiget.s"
	@echo "... micro-test/test_tailing.o"
	@echo "... micro-test/test_tailing.i"
	@echo "... micro-test/test_tailing.s"
	@echo "... test/test_dbcache.o"
	@echo "... test/test_dbcache.i"
	@echo "... test/test_dbcache.s"
	@echo "... test/test_graphdb.o"
	@echo "... test/test_graphdb.i"
	@echo "... test/test_graphdb.s"
	@echo "... test/test_simple.o"
	@echo "... test/test_simple.i"
	@echo "... test/test_simple.s"
	@echo "... test/test_strawman_join.o"
	@echo "... test/test_strawman_join.i"
	@echo "... test/test_strawman_join.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

